# Generated by Django 3.1.3 on 2020-11-23 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfiles', '0002_form'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article',
        ),
        migrations.AlterField(
            model_name='form',
            name='eMail',
            field=models.EmailField(max_length=40),
        ),
    ]
