# Generated by Django 3.1.3 on 2020-11-23 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfiles', '0003_auto_20201124_0041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='eMail',
            field=models.CharField(max_length=30),
        ),
    ]
