# Generated by Django 3.1.3 on 2020-11-23 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfiles', '0004_auto_20201124_0044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='eMail',
            field=models.EmailField(max_length=40),
        ),
    ]
