# Generated by Django 3.1.3 on 2020-11-23 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfiles', '0005_auto_20201124_0045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='eMail',
            field=models.EmailField(max_length=40, unique=True),
        ),
    ]
