# Generated by Django 3.1.3 on 2020-11-24 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfiles', '0006_auto_20201124_0046'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Form',
            new_name='UserProfiles',
        ),
    ]
