# Generated by Django 3.1.3 on 2020-11-24 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfiles', '0007_auto_20201125_0133'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserProfiles',
            new_name='UserProfile',
        ),
    ]
